name: Add Projects
description: Add your project(s) to the dicengineers.com/showcase site! Backlinks always help. If you have multiple, please add them as a list in the appropriate category.
title: "Add Project Request"
labels: ["add project"]
assignees:
  - mawburn
body:
  - type: input
    id: name
    attributes:
      label: Your name
      placeholder: Put your name, discord name, or github name here
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Your personal page
      description: If you have a personal site, social media, or github you want linked, put it here
      placeholder: (no emails)
    validations:
      required: false
  - type: textarea
    id: ttrpg
    attributes:
      label: TTRPGs
      description: TTRPG Related Projects
      placeholder: >
        - Project Name
          - Project Url
          - Short description. I may summarize this with ChatGPT to optimize SEO.
          - Icon url (optional)
    validations:
      required: false
  - type: textarea
    id: boardgames
    attributes:
      label: Boardgamess
      description: Boardgame / Card Game Related Projects
      placeholder: >
        - Project Name
          - Project Url
          - Short description. I may summarize this with ChatGPT to optimize SEO.
          - Icon url (optional)
    validations:
      required: false
  - type: textarea
    id: wargames
    attributes:
      label: Wargamess
      description: Wargame/Skirmish Game Related Projects
      placeholder: >
        - Project Name
          - Project Url
          - Short description. I may summarize this with ChatGPT to optimize SEO.
          - Icon url (optional)
    validations:
      required: false
  - type: textarea
    id: vtt
    attributes:
      label: VTT Related Projectss
      description: Virtual Tabletop Related Projects, plugins, extensions, etc.
      placeholder: >
        - Project Name
          - Project Url
          - Short description. I may summarize this with ChatGPT to optimize SEO.
          - Icon url (optional)
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Other Stuffs
      description: Anything that didn't fall into one of the above
      placeholder: >
        - Project Name
          - Project Url
          - Short description. I may summarize this with ChatGPT to optimize SEO.
          - Icon url (optional)
    validations:
      required: false
